#!/usr/bin/env python3
"""
Generate After Effects ExtendScript (.jsx) for template-based lower thirds.

Duplicates a hand-made AE template comp (_TEMPLATE_LT) for each person,
swaps text layers (txt_NAAM, txt_FUNCTIE), and places each on the timeline.

Usage:
    # From Python
    from generate_jsx import generate_jsx
    generate_jsx([
        {"name": "Jan Janssen", "title": "Directeur", "start": 10.5, "end": 14.2},
    ])

    # From CLI with CSV
    python generate_jsx.py --csv output/Sequence_01_1_lower_thirds.csv
    python generate_jsx.py --csv output/Sequence_01_1_lower_thirds.csv --fps 25
"""

import argparse
import csv
import os
import sys


def generate_jsx(data: list[dict], output_path: str = "output/import_lowerthirds.jsx") -> str:
    """Generate an AE ExtendScript that duplicates _TEMPLATE_LT for each entry.

    Args:
        data: List of dicts with keys: name, title, start (seconds), end (seconds)
        output_path: Where to write the .jsx file

    Returns:
        Path to the generated .jsx file
    """
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)

    # Build the JSX entries array as a string
    entries_js = []
    for entry in data:
        name_escaped = entry["name"].replace("\\", "\\\\").replace('"', '\\"')
        title_escaped = entry.get("title", "").replace("\\", "\\\\").replace('"', '\\"')
        entries_js.append(
            f'    {{name: "{name_escaped}", title: "{title_escaped}", '
            f'start: {entry["start"]:.4f}, end: {entry["end"]:.4f}}}'
        )
    entries_block = ",\n".join(entries_js)

    jsx = f"""/*
 * Lower Third Template Importer for After Effects
 * Generated by generate_jsx.py
 *
 * Duplicates _TEMPLATE_LT for each person, sets txt_NAAM and txt_FUNCTIE,
 * and places each on the active timeline at the correct timecodes.
 *
 * Usage: File > Scripts > Run Script File... > import_lowerthirds.jsx
 */

(function () {{
    var TEMPLATE_NAME = "_TEMPLATE_LT";
    var NAME_LAYER = "txt_NAAM";
    var TITLE_LAYER = "txt_FUNCTIE";

    var data = [
{entries_block}
    ];

    // ── Find template comp ──────────────────────────────────────────
    var templateComp = null;
    for (var i = 1; i <= app.project.numItems; i++) {{
        if (app.project.item(i).name === TEMPLATE_NAME && app.project.item(i) instanceof CompItem) {{
            templateComp = app.project.item(i);
            break;
        }}
    }}

    if (!templateComp) {{
        alert("Error: Template comp '" + TEMPLATE_NAME + "' not found in project.\\n\\nMake sure you have a composition named exactly: " + TEMPLATE_NAME);
        return;
    }}

    // ── Check active comp ───────────────────────────────────────────
    var mainComp = app.project.activeItem;
    if (!mainComp || !(mainComp instanceof CompItem)) {{
        alert("Error: No active composition.\\n\\nPlease open your main timeline composition first.");
        return;
    }}

    if (mainComp.name === TEMPLATE_NAME) {{
        alert("Error: The active comp is the template itself.\\n\\nPlease open your main timeline composition, not the template.");
        return;
    }}

    // ── Process entries ─────────────────────────────────────────────
    app.beginUndoGroup("Import Lower Thirds");

    var placed = 0;

    for (var i = 0; i < data.length; i++) {{
        var entry = data[i];

        // Duplicate template
        var newComp = templateComp.duplicate();
        newComp.name = "LT_" + entry.name;

        // Find and update txt_NAAM
        var nameLayer = null;
        for (var j = 1; j <= newComp.numLayers; j++) {{
            if (newComp.layer(j).name === NAME_LAYER) {{
                nameLayer = newComp.layer(j);
                break;
            }}
        }}

        if (!nameLayer) {{
            alert("Warning: Text layer '" + NAME_LAYER + "' not found in template.\\n\\nSkipping: " + entry.name + "\\n\\nMake sure your template has a text layer named exactly: " + NAME_LAYER);
            continue;
        }}

        // Set name text (preserve formatting)
        var nameDoc = nameLayer.property("ADBE Text Properties").property("ADBE Text Document").value;
        nameDoc.text = entry.name;
        nameLayer.property("ADBE Text Properties").property("ADBE Text Document").setValue(nameDoc);

        // Find and update txt_FUNCTIE
        var titleLayer = null;
        for (var j = 1; j <= newComp.numLayers; j++) {{
            if (newComp.layer(j).name === TITLE_LAYER) {{
                titleLayer = newComp.layer(j);
                break;
            }}
        }}

        if (!titleLayer) {{
            alert("Warning: Text layer '" + TITLE_LAYER + "' not found in template.\\n\\nSkipping title for: " + entry.name + "\\n\\nMake sure your template has a text layer named exactly: " + TITLE_LAYER);
        }} else {{
            var titleDoc = titleLayer.property("ADBE Text Properties").property("ADBE Text Document").value;
            titleDoc.text = entry.title;
            titleLayer.property("ADBE Text Properties").property("ADBE Text Document").setValue(titleDoc);
        }}

        // Add to main timeline
        var layer = mainComp.layers.add(newComp);
        layer.startTime = entry.start;
        layer.outPoint = entry.end;

        placed++;
    }}

    app.endUndoGroup();
    alert("Done! Placed " + placed + " lower third(s) on the timeline.");
}})();
"""

    with open(output_path, "w") as f:
        f.write(jsx)

    return output_path


# ─── CLI ─────────────────────────────────────────────────────────────────────

def timecode_to_seconds(tc: str, fps: float) -> float:
    """Convert SMPTE timecode HH:MM:SS:FF to seconds."""
    parts = tc.strip().split(":")
    if len(parts) != 4:
        return 0.0
    hh, mm, ss, ff = int(parts[0]), int(parts[1]), int(parts[2]), int(parts[3])
    return hh * 3600 + mm * 60 + ss + ff / fps


def main():
    parser = argparse.ArgumentParser(
        description="Generate AE ExtendScript for template-based lower thirds.",
    )
    parser.add_argument("--csv", required=True, help="Path to lower_thirds CSV file")
    parser.add_argument("--fps", type=float, default=25.0, help="Video frame rate for timecode conversion (default: 25)")
    parser.add_argument("--output", default=None, help="Output .jsx path (default: output/import_lowerthirds.jsx)")

    args = parser.parse_args()

    if not os.path.isfile(args.csv):
        sys.exit(f"Error: CSV file not found: {args.csv}")

    # Read CSV
    data = []
    with open(args.csv, newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            data.append({
                "name": row["name"].strip(),
                "title": row.get("title", "").strip(),
                "start": timecode_to_seconds(row["tc_in"], args.fps),
                "end": timecode_to_seconds(row["tc_out"], args.fps),
            })

    if not data:
        sys.exit("Error: No entries found in CSV.")

    output = args.output or "output/import_lowerthirds.jsx"
    path = generate_jsx(data, output)
    print(f"Generated {len(data)} lower third(s) → {path}")


if __name__ == "__main__":
    main()
