/*
 * Lower Third CSV Importer for After Effects
 *
 * Reads a CSV generated by face_detector.py and creates
 * lower third text layers at the correct timecodes.
 *
 * CSV format: name, title, tc_in, tc_out
 *
 * Usage:
 *   File > Scripts > Run Script File... > import_lower_thirds.jsx
 */

(function () {
    // ─── Config ─────────────────────────────────────────────────────
    var TITLE_SAFE_MARGIN = 0.10; // 10% on each side
    var BAR_OPACITY = 65;         // background bar opacity (0-100)
    var NAME_FONT_SIZE = 42;
    var TITLE_FONT_SIZE = 28;
    var FONT_NAME = "Liberation Sans";
    var NAME_COLOR = [1, 1, 1];          // white
    var TITLE_COLOR = [0.78, 0.78, 0.78]; // light grey
    var BAR_COLOR = [0, 0, 0];           // black

    // ─── Helpers ────────────────────────────────────────────────────

    function parseTimecode(tc, fps) {
        // Parse "HH:MM:SS:FF" to seconds
        var parts = tc.replace(/^\s+|\s+$/g, "").split(":");
        if (parts.length !== 4) return 0;
        var hh = parseInt(parts[0], 10);
        var mm = parseInt(parts[1], 10);
        var ss = parseInt(parts[2], 10);
        var ff = parseInt(parts[3], 10);
        return hh * 3600 + mm * 60 + ss + ff / fps;
    }

    function parseCSV(file) {
        var rows = [];
        file.open("r");
        var header = file.readln(); // skip header
        while (!file.eof) {
            var line = file.readln();
            if (line.replace(/^\s+|\s+$/g, "") === "") continue;
            // Split on comma, trim each value
            var parts = line.split(",");
            if (parts.length < 4) continue;
            rows.push({
                name: parts[0].replace(/^\s+|\s+$/g, ""),
                title: parts[1].replace(/^\s+|\s+$/g, ""),
                tc_in: parts[2].replace(/^\s+|\s+$/g, ""),
                tc_out: parts[3].replace(/^\s+|\s+$/g, "")
            });
        }
        file.close();
        return rows;
    }

    // ─── Main ───────────────────────────────────────────────────────

    // Check for active comp
    var comp = app.project.activeItem;
    if (!comp || !(comp instanceof CompItem)) {
        alert("Please open a composition first.");
        return;
    }

    // Pick CSV file
    var csvFile = File.openDialog("Select lower_thirds CSV file", "CSV:*.csv");
    if (!csvFile) return;

    var entries = parseCSV(csvFile);
    if (entries.length === 0) {
        alert("No entries found in CSV.");
        return;
    }

    var fps = comp.frameRate;
    var compW = comp.width;
    var compH = comp.height;

    // Title-safe positioning
    var marginX = compW * TITLE_SAFE_MARGIN;
    var marginY = compH * TITLE_SAFE_MARGIN;

    app.beginUndoGroup("Import Lower Thirds");

    for (var i = 0; i < entries.length; i++) {
        var entry = entries[i];
        var timeIn = parseTimecode(entry.tc_in, fps);
        var timeOut = parseTimecode(entry.tc_out, fps);
        var duration = timeOut - timeIn;
        if (duration <= 0) continue;

        // ── Background bar (shape layer) ────────────────────────
        var barLayer = comp.layers.addShape();
        barLayer.name = "LT Bar — " + entry.name;
        barLayer.startTime = timeIn;
        barLayer.outPoint = timeOut;

        // Estimate bar size based on text
        var barW = Math.max(entry.name.length, entry.title.length) * NAME_FONT_SIZE * 0.55 + 40;
        var barH = NAME_FONT_SIZE + TITLE_FONT_SIZE + 30;

        var shapeGroup = barLayer.property("ADBE Root Vectors Group").addProperty("ADBE Vector Group");
        var rect = shapeGroup.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Rect");
        rect.property("ADBE Vector Rect Size").setValue([barW, barH]);

        var fill = shapeGroup.property("ADBE Vectors Group").addProperty("ADBE Vector Graphic - Fill");
        fill.property("ADBE Vector Fill Color").setValue(BAR_COLOR);

        barLayer.transform.opacity.setValue(BAR_OPACITY);

        // Position bar: lower-left, title-safe
        var barX = marginX + barW / 2;
        var barY = compH - marginY - barH / 2;
        barLayer.transform.position.setValue([barX, barY]);

        // ── Name text layer ─────────────────────────────────────
        var nameLayer = comp.layers.addText(entry.name);
        nameLayer.name = "LT Name — " + entry.name;
        nameLayer.startTime = timeIn;
        nameLayer.outPoint = timeOut;

        var nameDoc = nameLayer.property("ADBE Text Properties")
                               .property("ADBE Text Document")
                               .value;
        nameDoc.font = FONT_NAME;
        nameDoc.fontSize = NAME_FONT_SIZE;
        nameDoc.fillColor = NAME_COLOR;
        nameDoc.applyFill = true;
        nameDoc.applyStroke = false;
        nameDoc.justification = ParagraphJustification.LEFT_JUSTIFY;
        nameLayer.property("ADBE Text Properties")
                 .property("ADBE Text Document")
                 .setValue(nameDoc);

        // Position name: lower-left, title-safe, above title line
        var nameX = marginX;
        var nameY = compH - marginY - TITLE_FONT_SIZE - 20;
        nameLayer.transform.position.setValue([nameX, nameY]);

        // ── Title text layer ────────────────────────────────────
        var titleLayer = comp.layers.addText(entry.title);
        titleLayer.name = "LT Title — " + entry.name;
        titleLayer.startTime = timeIn;
        titleLayer.outPoint = timeOut;

        var titleDoc = titleLayer.property("ADBE Text Properties")
                                  .property("ADBE Text Document")
                                  .value;
        titleDoc.font = FONT_NAME;
        titleDoc.fontSize = TITLE_FONT_SIZE;
        titleDoc.fillColor = TITLE_COLOR;
        titleDoc.applyFill = true;
        titleDoc.applyStroke = false;
        titleDoc.justification = ParagraphJustification.LEFT_JUSTIFY;
        titleLayer.property("ADBE Text Properties")
                  .property("ADBE Text Document")
                  .setValue(titleDoc);

        // Position title: just below the name
        var titleX = marginX;
        var titleY = compH - marginY - 5;
        titleLayer.transform.position.setValue([titleX, titleY]);
    }

    app.endUndoGroup();
    alert("Done! Placed " + entries.length + " lower third(s).");
})();
