/*
 * Lower Third Template Importer for After Effects
 * Generated by generate_jsx.py
 *
 * Duplicates _TEMPLATE_LT for each person, sets txt_NAAM and txt_FUNCTIE,
 * and places each on the active timeline at the correct timecodes.
 *
 * Usage: File > Scripts > Run Script File... > import_lowerthirds.jsx
 */

(function () {
    var TEMPLATE_NAME = "_TEMPLATE_LT";
    var NAME_LAYER = "txt_NAAM";
    var TITLE_LAYER = "txt_FUNCTIE";

    var data = [
    {name: "Jan Janssen", title: "Directeur", start: 0.0000, end: 4.8400},
    {name: "Marie Bakker", title: "Verslaggever", start: 10.0400, end: 14.9200},
    {name: "Peter de Vries", title: "Analist", start: 45.5600, end: 50.4400}
    ];

    // ── Find template comp ──────────────────────────────────────────
    var templateComp = null;
    for (var i = 1; i <= app.project.numItems; i++) {
        if (app.project.item(i).name === TEMPLATE_NAME && app.project.item(i) instanceof CompItem) {
            templateComp = app.project.item(i);
            break;
        }
    }

    if (!templateComp) {
        alert("Error: Template comp '" + TEMPLATE_NAME + "' not found in project.\n\nMake sure you have a composition named exactly: " + TEMPLATE_NAME);
        return;
    }

    // ── Check active comp ───────────────────────────────────────────
    var mainComp = app.project.activeItem;
    if (!mainComp || !(mainComp instanceof CompItem)) {
        alert("Error: No active composition.\n\nPlease open your main timeline composition first.");
        return;
    }

    if (mainComp.name === TEMPLATE_NAME) {
        alert("Error: The active comp is the template itself.\n\nPlease open your main timeline composition, not the template.");
        return;
    }

    // ── Process entries ─────────────────────────────────────────────
    app.beginUndoGroup("Import Lower Thirds");

    var placed = 0;

    for (var i = 0; i < data.length; i++) {
        var entry = data[i];

        // Duplicate template
        var newComp = templateComp.duplicate();
        newComp.name = "LT_" + entry.name;

        // Find and update txt_NAAM
        var nameLayer = null;
        for (var j = 1; j <= newComp.numLayers; j++) {
            if (newComp.layer(j).name === NAME_LAYER) {
                nameLayer = newComp.layer(j);
                break;
            }
        }

        if (!nameLayer) {
            alert("Warning: Text layer '" + NAME_LAYER + "' not found in template.\n\nSkipping: " + entry.name + "\n\nMake sure your template has a text layer named exactly: " + NAME_LAYER);
            continue;
        }

        // Set name text (preserve formatting)
        var nameDoc = nameLayer.property("ADBE Text Properties").property("ADBE Text Document").value;
        nameDoc.text = entry.name;
        nameLayer.property("ADBE Text Properties").property("ADBE Text Document").setValue(nameDoc);

        // Find and update txt_FUNCTIE
        var titleLayer = null;
        for (var j = 1; j <= newComp.numLayers; j++) {
            if (newComp.layer(j).name === TITLE_LAYER) {
                titleLayer = newComp.layer(j);
                break;
            }
        }

        if (!titleLayer) {
            alert("Warning: Text layer '" + TITLE_LAYER + "' not found in template.\n\nSkipping title for: " + entry.name + "\n\nMake sure your template has a text layer named exactly: " + TITLE_LAYER);
        } else {
            var titleDoc = titleLayer.property("ADBE Text Properties").property("ADBE Text Document").value;
            titleDoc.text = entry.title;
            titleLayer.property("ADBE Text Properties").property("ADBE Text Document").setValue(titleDoc);
        }

        // Add to main timeline
        var layer = mainComp.layers.add(newComp);
        layer.startTime = entry.start;
        layer.outPoint = entry.end;

        placed++;
    }

    app.endUndoGroup();
    alert("Done! Placed " + placed + " lower third(s) on the timeline.");
})();
